import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/header/Header'
import Feed from '../components/feed/Feed';
import SignUp from '../components/signup/SignUp';

export default function Home({ count, links }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Reddit like App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
      <Feed/>
      </main>
    </div>
  )
}

// export async function getStaticProps() {
//   const { count, allLinks } = await getAllLinks();
//   return {
//     props: {
//       count: count,
//       links: allLinks,
//     },
//   };
// }

